version: '2'
services:
  elasticsearch:
    # image: elasticsearch:5.0
    #   ^does not work yet
    image: elasticsearch:2.3
    # ports:
    #  - "9200:9200"
    volumes:
     - lanuv-elasticsearch-data:/usr/share/elasticsearch/data
     - lanuv-elasticsearch-config:/usr/share/elasticsearch/config

  logstash:
    image: logstash:2.3
    command: -f /etc/logstash/*.conf
    # docker run -it --rm -v "$PWD":/config-dir logstash logstash -f /config-dir/logstash.conf
    volumes:
      - ./volumes/logstash-config:/etc/logstash

    depends_on:
      - elasticsearch

  kibana:
    image: kibana:4.5
    depends_on:
      - elasticsearch

volumes:
  lanuv-elasticsearch-data:
  lanuv-elasticsearch-config:
